# setwd("tasks/audits/audit_lodes_construction_wages/code")
library(readr)
library(dplyr)
blocks <- read_csv("../output/block_construction_bins.csv", show_col_types = FALSE)
d <- read_csv("../output/district_construction_bins.csv", show_col_types = FALSE)
coverage <- blocks |> group_by(assignment) |> summarise(job_years = sum(total), .groups = "drop")
boroughs <- d |> filter(year == 0) |> group_by(borough) |> summarise(total = sum(total), low = sum(SE01)/total, middle = sum(SE02)/total, high = sum(SE03)/total, .groups = "drop")
pooled <- d |> filter(year == 0) |> arrange(share_SE03)
lines <- c("# LODES workplace construction findings", "", paste("Positive-construction block-years:", nrow(blocks)), paste("All NYC construction job-years:", sum(blocks$total)), "", "## Geographic coverage")
for (i in seq_len(nrow(coverage))) lines <- c(lines, paste(coverage$assignment[i], coverage$job_years[i], sep = ": "))
lines <- c(lines, "", "## Pooled borough shares within the 59 standard districts", "Borough | Job-years | <=1250 | 1251-3333 | >3333", "--- | ---: | ---: | ---: | ---:")
for (i in seq_len(nrow(boroughs))) lines <- c(lines, sprintf("%s | %d | %.1f%% | %.1f%% | %.1f%%", boroughs$borough[i], boroughs$total[i], 100*boroughs$low[i], 100*boroughs$middle[i], 100*boroughs$high[i]))
lines <- c(lines, "", "## District shares, ascending high-bin share", "District | Job-years | Share >3333", "--- | ---: | ---:")
for (i in seq_len(nrow(pooled))) lines <- c(lines, sprintf("%s %d | %d | %.1f%%", pooled$borough[i], pooled$boro_cd[i] %% 100, pooled$total[i], 100*pooled$share_SE03[i]))
lines <- c(lines, "", "All bins reconcile exactly to construction totals at each retained block-year. Pooled counts sum five annual observations; they are job-years, not unique workers. Workplace assignment and disclosure protection introduce nonsampling uncertainty. Bins are nominal monthly earnings, not hourly wages. Counts do not identify wages at particular developments.")
writeLines(lines, "../report/findings.md")
